# do not install anything extra onto the image
language: generic

# use a Mac OSX image
os: osx

# cache unity download#
cache:
  directories:
  - $UNITY_DOWNLOAD_CACHE

#  In order for Travis to save anything to the cache, you need to make
# sure itâ€™s writeable
before_install:
  - chmod a+x ./Scripts/*.sh

# send email notifications when the build changes from succeeding to broken
notifications:
  email:
    on_success: never
    on_failure: change

# run the script to download and install Unity editor
install:
- sudo -E sh ./Scripts/install.sh

# run the script for unit tests and builds
script:
- sudo -E sh ./Scripts/build.sh

# environment variables used in bash scripts
env:
  global:
  - UNITY_PROJECT_NAME="leVRnAlgebra"
  - UNITY_DOWNLOAD_CACHE="${TRAVIS_BUILD_DIR}/unity_download_cache"